"use client";
import {useEffect,useRef,useState} from 'react';
type Preview={status:number;preview?:{title:string;summary:string;redactionCount:number;lines:{speaker:string;time:string;text:string;match?:boolean}[]};previewHash?:string};
export function AiImportDialog({role,onClose,onSaved}:{role:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null),[interaction,setInteraction]=useState(role==='clinician'?'doctor':role==='nurse'?'nurse':'patient_ai'),[title,setTitle]=useState(''),[summary,setSummary]=useState(''),[messages,setMessages]=useState('[]'),[model,setModel]=useState('external-unverified'),[evidence,setEvidence]=useState('1'),[consent,setConsent]=useState(false),[reviewed,setReviewed]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal()},[]);
 const clear=()=>{setPreview(null);setReviewed(false)};
 const sample=()=>{const other=interaction==='doctor'?'clinician':interaction==='nurse'?'nurse':'ai';setMessages(JSON.stringify([{speaker:other,time:'00:00',text:'What would you like the care team to know?'},{speaker:'patient',time:'00:12',text:'Name: Demo Patient, SYNTHETIC_ID, phone SYNTHETIC_PHONE. I stopped my evening walks because symptoms begin sooner.'}],null,2));setTitle('Activity change awaiting review');setSummary('The patient reports stopping evening walks because symptoms begin sooner.');setEvidence('1');clear()};
 const run=async(save=false)=>{setBusy(true);setError('');try{const body={action:save?'import_ai_note':'preview_ai_import',interaction,title,summary,model,messages:JSON.parse(messages),evidence:evidence.split(',').map(v=>Number(v.trim())),syntheticConsent:consent,reviewedRedaction:reviewed,previewHash:preview?.previewHash};const r=await fetch('/api/care',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error??d.reason);if(save){await onSaved();onClose()}else setPreview(d)}catch(e){setError(e instanceof Error?e.message:'Unable to process import')}finally{setBusy(false)}};
 return <dialog ref={dialog} className="record-dialog" aria-labelledby="ai-import-title" onCancel={e=>{if(busy)e.preventDefault();else onClose()}}><header><div><h2 id="ai-import-title">Import AI summary</h2><small>Existing AI output + source messages · no paid model call</small></div><button aria-label="Close AI import" disabled={busy} onClick={onClose}>×</button></header><div className="record-dialog-body"><p className="voice-notice">Synthetic data only. Imported summaries remain AI GENERATED / REVIEW REQUIRED, not clinician-confirmed. All human participants must still approve full-chat access. Rule-based redaction is not exhaustive: inspect every preview.</p>
 <label>Interaction<select value={interaction} disabled={busy} onChange={e=>{setInteraction(e.target.value);clear()}}>{role==='clinician'&&<option value="doctor">Doctor–patient</option>}{['clinician','nurse'].includes(role)&&<option value="nurse">Nurse–patient</option>}<option value="patient_ai">AI–patient</option></select></label><button className="outline" disabled={busy} onClick={sample}>Use clearly labelled synthetic example</button>
 <label>Summary title<input value={title} maxLength={160} disabled={busy} onChange={e=>{setTitle(e.target.value);clear()}}/></label><label>Imported AI summary<textarea value={summary} maxLength={12000} disabled={busy} onChange={e=>{setSummary(e.target.value);clear()}}/></label><label>Source messages (JSON; speaker roles, source times, text)<textarea className="code-input" value={messages} disabled={busy} onChange={e=>{setMessages(e.target.value);clear()}}/></label><label>Evidence message indices (zero-based, comma-separated)<input value={evidence} disabled={busy} onChange={e=>{setEvidence(e.target.value);clear()}}/></label><label>Upstream model identifier (unverified)<input value={model} maxLength={80} disabled={busy} onChange={e=>{setModel(e.target.value);clear()}}/></label>
 <label className="check"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>{setConsent(e.target.checked);clear()}}/>I am authorized to import this simulated conversation; it contains no real patient data.</label>
 {error&&<p role="alert" className="voice-error">{error}</p>}
 {preview?.preview&&<section className="redaction-preview"><h3>Redacted processing preview · {preview.preview.redactionCount} replacements</h3><strong>{preview.preview.title}</strong><p>{preview.preview.summary}</p>{preview.preview.lines.map((m,i)=><p key={i}><b>{m.time} · {m.speaker}{m.match?' · evidence':''}</b><br/>{m.text}</p>)}<label className="check"><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/>I checked the redacted preview and evidence mapping. This is import review, not clinical confirmation.</label></section>}
 <div className="record-actions"><button className="outline" disabled={busy||!consent} onClick={()=>void run()}>Preview redaction</button><button className="primary" disabled={busy||!reviewed||!preview||!consent} onClick={()=>void run(true)}>{busy?'Processing…':'Import reviewed payload'}</button></div></div></dialog>;
}
