"use client";
import {useEffect,useRef,useState} from 'react';
type Snapshot={version:number;title:string;content:string;patient_visible:number;actor_id:string;action:string;created_at:string};
type History={currentVersion:number;canEdit:boolean;versions:Snapshot[]};
export function NoteHistory({entryId,initialVersion,onClose,onSaved,displayName}:{entryId:string;initialVersion?:number;onClose:()=>void;onSaved:()=>Promise<void>;displayName:(id:string)=>string}){
 const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState<History|null>(null),[selected,setSelected]=useState<number|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async(keepDraft=false)=>{const r=await fetch(`/api/entry-history?entryId=${encodeURIComponent(entryId)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setSelected(d.versions[0]?.version??null);if(!keepDraft){setTitle(d.versions[0]?.title??'');setContent(d.versions[0]?.content??'');setVisible(Boolean(d.versions[0]?.patient_visible))}};
 useEffect(()=>{dialog.current?.showModal();const controller=new AbortController();fetch(`/api/entry-history?entryId=${encodeURIComponent(entryId)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d}).then(d=>{setData(d);setSelected(initialVersion??d.versions[0]?.version??null);setTitle(d.versions[0]?.title??'');setContent(d.versions[0]?.content??'');setVisible(Boolean(d.versions[0]?.patient_visible))}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[entryId,initialVersion]);
 const close=()=>{if(busy)return;if(data?.canEdit&&(title!==data.versions[0]?.title||content!==data.versions[0]?.content||visible!==Boolean(data.versions[0]?.patient_visible))&&!window.confirm('Discard unsaved note changes?'))return;onClose()};
 const save=async(revert=false)=>{if(!data||busy)return;if(revert&&!window.confirm(`Restore v${selected} as a new version? All history is retained.`))return;setBusy(true);setError('');try{const r=await fetch('/api/care',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:revert?'revert_note':'edit_note',entryId,expectedVersion:data.currentVersion,title,content,patientVisible:visible,targetVersion:selected})});const result=await r.json();if(!r.ok)throw new Error(result.error??result.reason);await onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}};
 const snapshot=data?.versions.find(v=>v.version===selected),current=data?.versions[0];
 return <dialog ref={dialog} className="record-dialog" aria-labelledby="note-history-title" onCancel={e=>{e.preventDefault();close()}}><header><div><h2 id="note-history-title">Note history &amp; edit</h2><small>{entryId} · Current v{data?.currentVersion??'…'}</small></div><button aria-label="Close note history" disabled={busy} onClick={close}>×</button></header><div className="record-dialog-body">
 {error&&<p role="alert" className="voice-error">{error} Your unsaved draft is retained. <button disabled={busy} onClick={()=>void load(true).catch(e=>setError(e.message))}>Reload latest for comparison</button></p>}
 {!data&&!error&&<p>Loading permitted snapshots…</p>}
 {data&&<><label>Version<select value={selected??''} onChange={e=>setSelected(Number(e.target.value))}>{data.versions.map(v=><option key={v.version} value={v.version}>v{v.version} · {v.action} · {displayName(v.actor_id)}</option>)}</select></label>
 {snapshot&&<section className="snapshot"><h3>v{snapshot.version}: {snapshot.title}</h3><small>{new Date(snapshot.created_at).toLocaleString()} · {displayName(snapshot.actor_id)}</small>{snapshot.version!==current?.version?<div className="diff"><div className="removed"><strong>Selected version</strong><p>{snapshot.content}</p></div><div className="added"><strong>Current version</strong><p>{current?.content}</p></div></div>:<p>{snapshot.content}</p>}</section>}
 {data.canEdit?<><label>Title<input value={title} maxLength={160} disabled={busy} onChange={e=>setTitle(e.target.value)}/></label><label>Edit your role-owned note<textarea value={content} maxLength={12000} disabled={busy} onChange={e=>setContent(e.target.value)}/></label><label className="check"><input type="checkbox" checked={visible} disabled={busy} onChange={e=>setVisible(e.target.checked)}/>Patient-visible text (patient-owned updates always remain visible)</label><div className="record-actions"><button className="outline" disabled={busy||selected===data.currentVersion} onClick={()=>void save(true)}>Revert selected as new version</button><button className="primary" disabled={busy||!title.trim()||!content.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save new version'}</button></div></>:<p>Read-only: only the owning role can edit. AI source notes remain immutable; add a clinician correction separately.</p>}</>}
 </div></dialog>;
}
